### ISSUE TITLE
Hardcoded path in webpack-base-config.js

### ISSUE THREAD

**Issue by tokland** [dhis2/gis-app#112]
There is a hardcoded path to `Users/bjornadm/Sites/dhis2-gis-api/src/'`. See:

https://github.com/dhis2/dhis2-gis/blob/master/webpack-base-config.js#L21

**Comment by Markionium** [comment]
Is the path causing you any trouble?

This is there as a dev measure and we have not addressed it yet to be more dynamic. 

Thanks for pointing it out though :)

**Comment by tokland** [comment]
When I run `npm start` I have a import error. Changing it for `path.resolve(__dirname, '../dhis2-gis-api/src')` (with dhis2-gis-api cloned in the parent directory), it works.

**Comment by Markionium** [comment]
Right, yes i guess we could temporarily change it to that as a make due solution.
