### ISSUE TITLE
Determine an approach to deal with clustered events and reaching the zoom limit

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/gis-app#146]
![image](https://cloud.githubusercontent.com/assets/2968061/17510675/380af570-5e20-11e6-9d0f-e9927b55b306.png)

There are two events which appear to have the same lat/long, which of course can occur, especially with data which has been geocoded or obtained from remote sensing stations (with a fixed location). 

When reaching the zoom limit, it is impossible to click the cluster and see the individual events.

**Comment by turban** [comment]
This seems to work now. Please notify if you're experiencing the issue again. 

![screen shot 2016-11-29 at 16 13 51](https://cloud.githubusercontent.com/assets/548708/20715442/84fc0266-b64f-11e6-87ec-1ff5e9301a41.png)
