### ISSUE TITLE
GIS does double PUT when overwriting a favorite

### ISSUE THREAD

**Issue by mortenoh** [dhis2/gis-app#165]
Load up any favorite, open favorite dialog, and overwrite.. it sends two PUTs to save.. one fails, and one succeeds..

<img width="1369" alt="screen shot 2016-09-08 at 11 03 44" src="https://cloud.githubusercontent.com/assets/84345/18336777/558c9d14-75b4-11e6-880c-5f0a63b51c66.png">

<img width="1395" alt="screen shot 2016-09-08 at 11 03 51" src="https://cloud.githubusercontent.com/assets/84345/18336778/58a2bb50-75b4-11e6-8361-08b7697b5b2a.png">

**Comment by turban** [comment]
"name" is now a required field. I've added the same name in the PUT, and it solved the issue.

**Comment by turban** [comment]
Fixed in trunk.
