### ISSUE TITLE
Overwriting favorite makes it invalid

### ISSUE THREAD

**Issue by mortenoh** [dhis2/gis-app#166]
Load up any favorite, open favorite dialog, overwrite it, try to load it again.

<img width="1346" alt="screen shot 2016-09-08 at 11 04 34" src="https://cloud.githubusercontent.com/assets/84345/18336788/7a4babc2-75b4-11e6-9d7b-126ee0dc7b52.png">

**Comment by turban** [comment]
Fixed in trunk.
