### ISSUE TITLE
OSM layer fails to load

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/gis-app#176]
Failed to load resource: net::ERR_INSECURE_RESPONSE

Seems to be a problem with OSM NET::ERR_CERT_COMMON_NAME_INVALID

for instance to https://a.tile.osm.org/8/121/122.png

**Comment by turban** [comment]
We need to change to this URL which supports https:
https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
