### ISSUE TITLE
Search location hits: Map pin not shown

### ISSUE THREAD

**Issue by Bekkalizer** [dhis2/gis-app#179]
When opening the GIS app on play.dhis2.org/dev, and searching for "Freetown"(I guess anything, with a hit, really) - the map pin is not properly displayed:
<img width="302" alt="skjermbilde 2016-09-30 kl 11 25 52" src="https://cloud.githubusercontent.com/assets/12655979/18987330/624b07bc-8701-11e6-94eb-137f81453b97.png">

**Comment by turban** [comment]
Fixed in trunk.
