### ISSUE TITLE
Pinning search results

### ISSUE THREAD

**Issue by Bekkalizer** [dhis2/gis-app#180]
There seems to be an issue when searching and pinning search results. When searching "Frankfurt"(and _pressing enter_ to update the hit list) in the GIS app, three search results is displayed:
<img width="791" alt="skjermbilde 2016-09-30 kl 11 40 51" src="https://cloud.githubusercontent.com/assets/12655979/18987662/fc4557ea-8702-11e6-9768-ffc042e55263.png">

When clicking the top hit, the map zooms but no pin is set.
When clicking either of the two other hits, the map zooms, and a pin is set.

**Comment by turban** [comment]
Not able to reproduce locally - let's test again on play dev when it's updated. Might have been solved with: https://github.com/dhis2/gis-app/issues/179

**Comment by Bekkalizer** [comment]
Also reported in https://freedcamp.com/DHIS_2_Software_Deve_cBT/DHIS_225_Releas_PCm/todos/7239212/

**Comment by Bekkalizer** [comment]
Cant repro in dev any longer.
