### ISSUE TITLE
Plugin left/right click imperfections

### ISSUE THREAD

**Issue by janhenrikoverland** [dhis2/gis-app#193]
![screenshot from 2016-10-26 15 54 53](https://cloud.githubusercontent.com/assets/1010094/19729526/8f1774c4-9b97-11e6-8fd7-7dda0acce3f0.png)

**Comment by turban** [comment]
Styling and translation issues fixed. 

![screen shot 2016-11-23 at 14 44 23](https://cloud.githubusercontent.com/assets/548708/20564015/62895c10-b18b-11e6-8a7e-996d05811daf.png)
