### ISSUE TITLE
Aggregation type option for thematic layers

### ISSUE THREAD

**Issue by larshelge** [dhis2/gis-app#56]
Add option for defining "aggregation type" for thematic layers.

API docs: http://dhis2.github.io/dhis2-docs/master/en/developer/html/webapi_analytics.html#webapi_analytics_query_parameters

Similar to pivot table and data visualizer.

![agg](https://cloud.githubusercontent.com/assets/908206/14234515/db45532a-f9e4-11e5-97ad-c6a9f4b08745.png)

SUM | AVERAGE | COUNT | STDDEV | VARIANCE

**Comment by turban** [comment]
- [ ] Save aggregation type with favorite.
