### ISSUE TITLE
Download map support

### ISSUE THREAD

**Issue by turban** [dhis2/gis-app#7]
It's currently possible to download a map as a PNG, but it only works for for vector overlays and not base maps. We should remove or improve this feature. 

The best option will probably be to use a headless browser (e.g. PhantomJS) to programmatically capture map contents. This should work with all layer types supported by Leaflet. 

An alternative is to do this in the browser, which requires all map layers to be drawn with Canvas. This will probably be more complicated to implement. 

https://blueprints.launchpad.net/dhis2/+spec/gis-download-facility-layer

**Comment by turban** [comment]
Download button is removed until we find a better map capture solution.

**Comment by turban** [comment]
html2canvas: https://github.com/niklasvh/html2canvas
canvas2image: https://github.com/hongru/canvas2image

https://jsfiddle.net/8ypxW/3/

**Comment by mortenoh** [comment]
Another option would be to open another window with the same rendering
options (but set to e.g. a4 dimensions) and then just print.. its a bit
more messy, but is similar to what google maps is doing, while this doesn't
allow us to "get PNG", the user could easily print to PDF with background
maps etc intact..

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org

**Comment by turban** [comment]
Bug that should be fixed when a new map export solution is in place: https://bugs.launchpad.net/dhis2/+bug/1606383
