### ISSUE TITLE
Default icon for Org unit groups without symbol?

### ISSUE THREAD

**Issue by Markionium** [dhis2/gis-app#93]
Not really a bug, just a minor thing

![image](https://cloud.githubusercontent.com/assets/2134901/14522790/8be50c22-0230-11e6-9f71-f436872071c5.png)

**Comment by turban** [comment]
There are already 6 coloured circles in the /images/orgunitgroup/ folder. I'm using these as defaults for org.unit groups without a symbol. 

![screen shot 2016-09-16 at 13 39 57](https://cloud.githubusercontent.com/assets/548708/18584771/42a6393e-7c13-11e6-9aa7-111179a47586.png)

We should change to some better looking icons at a later stage.

Candidates:
https://www.mapbox.com/maki/
http://reliefweb.int/report/world/world-humanitarian-and-country-icons-2012
http://map-icons.com/
