### ISSUE TITLE
UX Observation around data element dimension selection

### ISSUE THREAD

**Issue by Markionium** [dhis2/gis-app#94]
When trying to create a map around ART Enrollment i noticed that when changing the Totals/Details dropdown, the options in the Data Element dropdown change (which makes sense from a technical perspective as they represent full data elements and/or the disaggregated ones) but from a more usability perspective this feels wrong (as it clears out a dropdown i just filled)

![image](https://cloud.githubusercontent.com/assets/2134901/14523033/c83e5d58-0231-11e6-8c64-c34afcfb86bd.png)

I feel that it would make more sense to have the dropdown box for Details/Totals have a different range of values. Namely _Totals_ and the Disaggregated options like _Female / 15-24y_, _Male 15-24y_ etc.

The first dropdown could then contain the data elements that are present in the selected data element group.
Where the second dropdown would then contain a choice between totals or a disaggregated value so for ART Enrollment stage 1 when opening the dropdown the values could be.
- Totals
- Female, 15-24y
- Female, 24-49y
- Female, > 49y
- Male, 15-24y
- Male, 24-49y
- Male, > 49y

This would greatly reduce the amount of items in the dropdown as it would only show the disaggregations for that data element rather than for all the data elements in the group. I (and Rachel ;)) also believe it would make the UI a bit more intuitive.

**Comment by turban** [comment]
Moved to JIRA: https://jira.dhis2.org/browse/DHIS2-308
